# Style detection configuration
# Controls behavior of style analysis during document conversion
# Users can override these settings in ~/.orlando_toolkit/style_detection.yml

# Enable structural style inference (adds missing heading styles based on content patterns)
enable_structural_style_inference: true

# Minimum number of following paragraphs to consider when analyzing structure
min_following_paragraphs: 3

# Enable generic heading pattern matching (e.g., "HEADING 5 GM")
generic_heading_match: true